---
- name: Install some package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - wget
    - yum utils
    - git
    - python3
    - python3-pip
    - lvm2
    - device-mapper-persistent-data
- name: add docker repository
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/centos/7/X86_64/stable
    enabled: yes
- name: add gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state:present
- name: install docker
  package:
    name:
    - docker-ce
    - docker-ce-cli
    state: latest

- name: install docker-compose
  get_url:
    url: "https://githu.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
    dest: /usr/local/bin/docker-compose
    mode: 755
- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify : restart docker

- name: installe docker python package
  pip:
    name: docker-py
    state: present
    executable: pip3
