---
# name: Preparation et Installation de Docker
  #hosts: all
  #become: true

  vars:
    docker_centos_repo_baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable"
    docker_compose_version: "2.24.6"
    user_to_add_to_docker_group: "{{ ansible_user }}"

  tasks:
    - name: Installer les paquets requis
      package:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - wget
        - yum-utils
        - git
        - python3
        - python3-pip
        - lvm2
        - device-mapper-persistent-data

    - name: Configurer le dépôt Docker
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: "{{ docker_centos_repo_baseurl }}"
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Installer Docker CE, CLI et containerd.io
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
      notify: start docker

    - name: Installer Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ajouter l'utilisateur au groupe Docker
      user:
        name: "{{ user_to_add_to_docker_group }}"
        groups: docker
        append: yes
      notify: restart docker

    - name: Installer le package Python Docker
      pip:
        name: docker
        state: present
        executable: pip3

  handlers:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: restart docker
      service:
        name: docker
        state: restarted
