---
- name: Update OS
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - python3
    - python3-pip
    - ca-certificates
    - gnupg
    - lsb-release
    - unzip
    - apt-transport-https
    - software-properties-common

- name: Install Docker
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 755

- name: Docker start deploy
  command: sh /tmp/get-docker.sh
  become: true

- name: Check Docker group
  group:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true
  notify: restart docker

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
    dest: /usr/local/bin/docker-compose
    mode: 755
