---
- name: Installer les paquets requis
  package:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - wget
    - yum-utils
    - git
    - python3
    - python3-pip
    - lvm2
    - device-mapper-persistent-data

- name: Configurer le dépôt Docker
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - {{ ansible_architecture }}
    baseurl: "{{ docker_centos_repo_baseurl | default('https://download.docker.com/linux/centos/$releasever/$basearch/stable') }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_os_family == "RedHat"

- name: Ajouter la clé GPG Docker pour Ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Configurer le dépôt Docker pour Ubuntu
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_os_family == "Debian"

- name: Installer Docker CE, CLI et containerd.io (CentOS)
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  notify: start docker
  when: ansible_os_family == "RedHat"

- name: Installer Docker CE, CLI et containerd.io (Ubuntu)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  notify: start docker
  when: ansible_os_family == "Debian"

- name: Installer Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version | default('v2.20.2') }}/docker-compose-linux-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ajouter l'utilisateur au groupe Docker
  user:
    name: "{{ user_to_add_to_docker_group }}"
    groups: docker
    append: yes
  notify: restart docker

- name: Installer le package Python Docker
  pip:
    name: docker
    state: present
    executable: pip3
